### ISSUE TITLE
No attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by PepijnBoers** [stared/livelossplot#100]
I came across an attribute error, when running a simple fit function that has always worked with livelossplot.

My code:
```
from livelossplot import PlotLossesKeras
model.fit(X_images, y_images, validation_data=(X_val_images, y_val_images), epochs = 50, callbacks=[PlotLossesKeras()])
```

This gave the following error:
`AttributeError: 'PlotLossesCallback' object has no attribute '_implements_train_batch_hooks'`

Code runs fine without the callback.

**Comment by PepijnBoers** [comment]
Error caused by using Tensorflow version 2. Issue resolved in Google Colab by running following code before importing Tensorflow:

`%tensorflow_version 1.x`

**Comment by TheCrazyT** [comment]
are there any plans on making this work with version 2 of tensorflow?
