### ISSUE TITLE
log scale

### ISSUE THREAD

**Issue by je-santos** [stared/livelossplot#102]
Hi,

would it be possible to add an option to make the axis log?
I have it hard coded, but this might be a feature that more people would like :)

Thanks!

**Comment by stared** [comment]
Thanks for this feedback, @je-santos! 

We are investigating how to balance features, and which things to add custom plots.

**Comment by stared** [comment]
Some things needed rewrite, but with `0.5.2` it is possible:  <https://github.com/stared/livelossplot/blob/master/examples/matplotlib.ipynb>

```
def custom_after_subplot(ax: plt.Axes, group: str, x_label: str):
    """Make logarithmic scale on loss chart"""
    if group == 'log-loss':
        ax.loglog()
    ax.set_xlabel(x_label)
   
outputs = [MatplotlibPlot(after_subplot=custom_after_subplot)]
...
```

![image](https://user-images.githubusercontent.com/1001610/87883188-03c3ce80-ca06-11ea-9eb6-373b3983bcbb.png)

Let me know it works for you!

We wanted to make it flexible (in particular - you can do this only for some metrics, or modify other options),
