### ISSUE TITLE
KeyError : 'metrics'     Please Help

### ISSUE THREAD

**Issue by hemangjoshi37a** [stared/livelossplot#104]
This error has started appearing after I upgraded my tensorflow version to 2.2

> 
> ~/.local/lib/python3.5/site-packages/livelossplot/generic_keras.py in on_train_begin(self, logs)
>      29 
>      30     def on_train_begin(self, logs={}):
> ---> 31         self.liveplot.set_metrics([metric for metric in self.params['metrics'] if not metric.startswith('val_')])
>      32 
>      33         # slightly convolved due to model.complie(loss=...) stuff
> 
> KeyError: 'metrics'

**Comment by kaanakdeniz** [comment]
If you should import just keras
`import keras` it'll work.
I don't know why but tensorflow keras is not working.

**Comment by stared** [comment]
@hemangjoshi37a Coul you post the lines of code causing this error?

**Comment by hemangjoshi37a** [comment]
This is the code sir... @stared 

```
model.compile(optimizer=keras.optimizers.adam(), loss='mean_squared_error',metrics=["accuracy"])
history=model.fit(x_train, y_train,validation_split=0.05, verbose=1, batch_size=1000, epochs=5,callbacks=[livelossplot.PlotLossesKeras(),WandbCallback()])
```

**Comment by hemangjoshi37a** [comment]
> If you should import just keras
> `import keras` it'll work.
> I don't know why but tensorflow keras is not working.
> And you should ` from livelossplot.keras import PlotLossesCallback`
> model.fit callback = `callbacks=[PlotLossesCallback()])`

I cant use keras instead of the tfkeras because it does not work with my other code. So it is not a option.
But anyway sir thank you very much for replying.

**Comment by stared** [comment]
@hemangjoshi37a Could you copy&paste all import lines (relevant to livelossplot, Keras and TensorFlow)?

**Comment by megha-a7** [comment]
I was still getting the error. Then I followed this - 

I did `import keras` 

Then changed the import statement

`from livelossplot.tf_keras import PlotLossesCallback
`
to

`from livelossplot.inputs.tf_keras import PlotLossesCallback`

**Comment by stared** [comment]
@megha-a7  Please show the full part with the import and versiona of TensorFlow and Keras.

If you use standalone `keras,` you need to use  `livelossplot.keras`, not `livelossplot.tf_keras`.
