### ISSUE TITLE
install error in python 2.7

### ISSUE THREAD

**Issue by scionk** [stared/livelossplot#12]
in setup.py

def readme():
    with open('README.md', encoding='utf-8') as f:
        return f.read()
...
long_description=readme()

but, in python 2.7, open function has no encoding parameter.
so, error occurs.
"TypeError: 'encoding' is an invalid keyword argument for this function"

**Comment by stared** [comment]
It was introduced by https://github.com/stared/livelossplot/pull/9 by @jonahweissman to make sure it works well in Python 3, regardless of default encoding.

I would need to check a solution that works on both Python 2.7 and Python 3.5+. Ideas?

**Comment by scionk** [comment]
How about this?

from io import open

Then, it'll work 2.7 and 3.6 both versions.

**Comment by stared** [comment]
@scionk thanks!
(I see it's here: https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2/10971047#10971047)

Solved with https://github.com/stared/livelossplot/commit/4b9cca444ca659b1194504dd0b4c78d1d8e7afb4.

**Comment by JeSTeRFLA** [comment]
simplest fix would be:
`with open('README.md', encoding='utf-8') as f:`
Remove the encode string on a system that is already UTF-8
`with open('README.md') as f:` 
That way the system don't have to argue with python about encoding at all. 
ONLY WORKS ON SYSTEMS ALREADY UTF-8 !!!!!!!
