### ISSUE TITLE
Sudden error that wasn't happen before - index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by kithevans** [stared/livelossplot#121]
When I use newest version of liveossplot(0.5.2), an error popped up
'index 0 is out of bounds for axis 0 with size 0'

I apply PlotLossesKerasTF() as callbacks,
and version 0.5.1 is still working well.

There must be a bug and It should be fixed.
Thanks!

**Comment by stared** [comment]
We just released `0.5.3` that fixes that issue (thanks to @Bartolo1024).
