### ISSUE TITLE
sliding start of epochs

### ISSUE THREAD

**Issue by kolban-google** [stared/livelossplot#124]
On the X-Axis, we have the epoch starting at 0.  This means that as I train more, the graphs are getting "scrunched" in width.  Would it be possible to add the ability to define the width of the graphs in epochs?  For example, if I define 100 then the graph will grow to show 0-99 but as I pass that the graph will show 1-100 and then 2-101, and 3-102.  Basically a sliding/scrolling graph showing my last 100 epochs?

**Comment by stared** [comment]
@kolban-google Thanks for asking. We plan to add it in the next edition.

**Comment by stared** [comment]
Now it works, in livelossplot `0.5.4`.

```
plotlosses = PlotLosses(from_step=...)
```

For positive numbers, it is "start from the epoch n":

<img width="1100" alt="Screenshot 2021-02-03 at 17 28 24" src="https://user-images.githubusercontent.com/1001610/106777404-41581400-6645-11eb-94b7-b7f81ef567a6.png">

For negative, it is "show only last n epochs":
![Uploading Screenshot 2021-02-03 at 17.29.55.png…]()
