### ISSUE TITLE
Need help to force the "inline" matplotlib backend when running scripts from Jupiter notebook

### ISSUE THREAD

**Issue by sebma** [stared/livelossplot#13]
Hi,

I'd like my script to automatically change the backend back to "inline" when it is run by Jupiter.

I tried this but it does not work (in practice) : 

```python
# If the script is not run by python but by jupyter and is using a different backend then "inline"
if matplotlib.get_backend() != 'Qt5Agg' and ( 'inline' not in matplotlib.get_backend() ) :
    print("=> BEFORE: matplotlib backend = <%s>" % matplotlib.get_backend() )
    matplotlib.use('module://ipykernel.pylab.backend_inline',warn=False, force=True) # <=> %matplotlib inline
    import matplotlib.pyplot as plt
    print("=> AFTER: matplotlib backend = <%s>" % matplotlib.get_backend() )
```

I get this (which theoretically is correct) : 
```python
=> BEFORE: matplotlib backend = <nbAgg>
=> AFTER: matplotlib backend = <module://ipykernel.pylab.backend_inline>
```

But in practice, the "inline" backend is not applied.

Can you help me ?

**Comment by stared** [comment]
@sebma  I wish I knew how to do that. 

If you learn how to do so, make sure to share it here!

**Comment by stared** [comment]
@sebma Since there is no progress in the last year, I close that. Open for opening in case of Pull Requests.
