### ISSUE TITLE
PlotLossesKeras stops if tensorflow.keras is used without installing traditional keras

### ISSUE THREAD

**Issue by makonori** [stared/livelossplot#132]
## 🚀 Feature
PlotLossesKeras stops at 'import keras' of keras.py when users use tensorflow.keras without installing stand-alone keras. Currently, we can see two types of Keras, tensorflow.keras and keras. If the users install the old keras, no problem. However, I personally think that it is better to support tensorflow.keras users. Thank you for the developper's kindness.

**Comment by ck37** [comment]
Please use PlotLossesKerasTF() instead of PlotLossesKeras() - does that resolve the issue?

**Comment by makonori** [comment]
thank you for your kindness
