### ISSUE TITLE
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating

### ISSUE THREAD

**Issue by isalirezag** [stared/livelossplot#15]
Maybe fix this warning for the future:

```
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
```

**Comment by stared** [comment]
Unless I miss something, it's a TensorFlow vs NumPy error, having nothing to do with `livelossplot` per se.

See: https://stackoverflow.com/questions/48340392/futurewarning-conversion-of-the-second-argument-of-issubdtype-from-float-to/48774337
