### ISSUE TITLE
Adding Bokeh backend

### ISSUE THREAD

**Issue by stared** [stared/livelossplot#19]
[Bokeh](https://bokeh.pydata.org/en/latest/), as an alternative backend to [matplotlib](https://matplotlib.org/), would make it simple to:

* toggle between in-notebook plots and external plots (so that it would work seamlessly with both Jupyter Notebook Python scripts) 
* give mouseover view of exact numerical values (no more eye squeezing!)
* zoom if needed

I don't want to have it instead of `matplotlib` (as this one makes it easier to save plots, so that they are visible in Jupyter Notebooks on GitHub), but as an additional backend.

My experience with Bokeh is limited, so this issue is open for YOUR contribution! :)

**Comment by stared** [comment]
VIde: https://github.com/bokeh/bokeh/blob/master/examples/howto/notebook_comms/Continuous%20Updating.ipynb

**Comment by xysong1201** [comment]
Hi, in my case, if I use 
```
import matplotlib
matplotlib.use('TkAgg')
```
my code works fine, so could you add this to your code

**Comment by stared** [comment]
@xysong1201 I delete it as it is not related to Bokeh at all. Start a new thread and explain what's the issue.

**Comment by stared** [comment]
See #57 for a PR.

**Comment by stared** [comment]
There is an initial version with #82 released in 0.5.0.

```
from livelossplot.outputs import BokehPlot
```

**Comment by stared** [comment]
@Bartolo1024 It appears that Bokeh works in Colab: https://colab.research.google.com/notebooks/charts.ipynb#scrollTo=N-u5cYwpS-y0 (from https://github.com/googlecolab/colabtools/issues/23).

**Comment by stared** [comment]
See #106
