### ISSUE TITLE
Axis scaling when using with early stopping

### ISSUE THREAD

**Issue by roboserg** [stared/livelossplot#21]
I have epochs = 99 because I use early stopping. The problem is that the plot scales the x axis for the number of epochs I set, not the actual number of epochs. 

I would like the plot automatically adjust to the number of current, real, epochs. Otherwise the plot looks like this and is very poorly readable - https://puu.sh/BoxPa/5a3c0ee3bb.png

**Comment by stared** [comment]
Use `dynamic_x_axis=True` parameter.
