### ISSUE TITLE
TypError: int object is not callable

### ISSUE THREAD

**Issue by NexusHero** [stared/livelossplot#22]
It the end of the validation process it throws an TypError at the line:

draw_plot(logs, metrics, figsize, max_epoch, max_cols, validation_fmt, metric2title)
     26 
     27         if max_epoch is not None:
---> 28             plt.xlim(1, max_epoch)
     29 
     30         plt.plot(range(1, len(logs) + 1),

TypeError: 'int' object is not callable 

How can i prevent this?

**Comment by stared** [comment]
@NexusHero  This is a vague error message, I cannot decipher it without knowing the full code. (Most likely some wrong parameter values for `draw_plot`)
