### ISSUE TITLE
Support for x-axis that is not an epoch

### ISSUE THREAD

**Issue by turian** [stared/livelossplot#23]
I would like to be able to override the label for the x-axis.
Also, sometimes I would like to explicitly give the x-value for one of the points.

For example, if you are doing minibatch training, you might give the x-axis as the total number of examples seen.

Also, you might want to have training points every minibatch, and validation points at the end of every epoch, and the xvalue is minibatch * nbatches

**Comment by stared** [comment]
It is a good idea, please write a Pull Requests. 
E.g. `samples_per_update=None`. If `None` then as usual, if different - then xlabel to `samples` Xs multiplied by this.

**Comment by jn8029** [comment]
Hi,

I am trying to see if I can get this implemented.. for fun.  and have a question regarding what exactly should be displayed on the x-axis.

Assuming:
train_size = 10,000
batch_size = 500
epoch = 10

Would you like to see on the x-axis labels: 

500 1000 1500 2000 .... 10000, 500, 1000, 1500..... 10000? (restart at 500 for each new epoch)

or you'd like to see the cumulative number of samples that the model has seen through.. i.e.
500 1000 1500 2000........99500 100000  (10 epochs, so total number of samples seen is 100k)


Thanks.

**Comment by stared** [comment]
@jn8029 For sure the later (making it incremental). Not incremental x-axis is a mess.

**Comment by stared** [comment]
Added with b9b7f126c51b703f06964b90d89626844a019101. When using 

```
livelossplot.update(logs, step=5)```

to have a step of 5 (instead of 1).

Will start with version `0.4.0` and higher.
