### ISSUE TITLE
where is the dynamic_x_axis?

### ISSUE THREAD

**Issue by qinst64** [stared/livelossplot#30]
how to set a dynamic x axis which was available in the previous version as `dynamic_x_axis=True`?

**Comment by qinst64** [comment]
ok I read the code and found 
the previous `self.params['epochs'] if not self.dynamic_x_axis else None`
is now missing, and now simply `self.liveplot.max_epoch = self.params['epochs']`.
pls fix

**Comment by stared** [comment]
#35 by @kkanska should solve that.
