### ISSUE TITLE
New graph for every epoch

### ISSUE THREAD

**Issue by MikeH3N** [stared/livelossplot#4]
Hi,

I'm getting this error 'RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)'

It seems to be opening a new graph for every epoch, anyone know a fix for this?

**Comment by stared** [comment]
Please provide information about your environment (Python, Matplotlib and Jupyter versions). 
And make sure you run in `%matplotlib inline` mode.

**Comment by utausheva** [comment]
hah, got the same error again) shell i start new issue?

**Comment by stared** [comment]
With the new update https://github.com/stared/livelossplot/commit/45b152d259d8a282bdb01104bb7d23df64abed08 I explicitly check for matplotlib inline backend. 

It does not support other environments. While pull requests may be welcome (as long as they add functionality and don't break anything), I won't myself on PyCharm (I don't use one).
