### ISSUE TITLE
adding matplotlib.use('TkAgg')

### ISSUE THREAD

**Issue by xysong1201** [stared/livelossplot#41]
Hi, I'd like to use the plot in the case that I can output using nohup command, but as there is a problem of GUI, so it caused segmentation core broke, so I can't plot in the output file. adding `matplotlib.use('TkAgg')` in this case may solve my problem but I'm not sure in your codes where to modify it.
In any case, it works fine in Jupyter Notebook, thank you!

**Comment by stared** [comment]
@xysong1201 Thank you for opening it as a new issue.

 Please specify issue or a feature request. `adding matplotlib.use('TkAgg')` alone is crypthic.
