### ISSUE TITLE
add X-label interval 

### ISSUE THREAD

**Issue by xysong1201** [stared/livelossplot#42]
Hi, I used your codes for plotting many epochs, and as there are a lot epochs, the xlabel only show 5, 10, 15, etc. Could you tell me how to exactly know which epoch my loss point belongs to? Maybe `my_x_ticks = np.arange(0, 200, 1)
        my_y_ticks = np.arange(0, 1, 0.01)
        plt.xticks(my_x_ticks)
        plt.yticks(my_y_ticks)`
something like this may help.
Thankyou for your time

**Comment by stared** [comment]
We use default matplotlib settings for plots. 

I plan to add a possibility to add custom plots, with all possible changes (yes, including ticks, colors, label location, etc).

**Comment by stared** [comment]
Added with b9b7f126c51b703f06964b90d89626844a019101. When using 

```
livelossplot.update(logs, step=5)```

to have a step of 5 (instead of 1).

Will start with version `0.4.0` and higher.
