### ISSUE TITLE
How can I inline with OS X?

### ISSUE THREAD

**Issue by shamoons** [stared/livelossplot#43]
I'm not running from a Jupyter notebook, instead I'm running in Python directly (on OS X). How can I force inline?

**Comment by stared** [comment]
@shamoons Please provide a full description. If you mean writing scripts from Terminal (it's not called inline), as in `$ python3 my_script.py`, then so far it isn't possible.

How do you envision that?

With Bokeh interface, or after adding Neptune connectors, it will be possible, but it is still in the roadmap.

**Comment by shamoons** [comment]
Correct, I'm running from terminal. I'm not sure to be honest. Maybe some sort of opencv implementation for live updates?
