### ISSUE TITLE
Y-axis support

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [stared/livelossplot#44]
HI, 

Please let me know how I can change the values of Y axis for log loss in x.xxx format and acc in x.xxx format

**Comment by stared** [comment]
@Jayan-K-Duggal Right now it uses default `matplotlib` settings, and it is not possible to change that.

I plan to add custom plots at some point.

**Comment by Jayan-K-Duggal** [comment]
Thank you, I figured it out.

**Comment by miretchin** [comment]
> Thank you, I figured it out.

What did you end up doing?

**Comment by Jayan-K-Duggal** [comment]
Let me check, I will answer this give me some time.
