### ISSUE TITLE
[QUESTION] Is there any way to get it to work with TensorFlow?

### ISSUE THREAD

**Issue by lucasfariaslf** [stared/livelossplot#45]
I've noticed the answer to the (The Most FA)A, but I've been trying to find a way, looking at the minimal bare API example and TF's training interactions, to make it work in a TF environment. 

Has anyone been succcessful at this?

**Comment by stared** [comment]
@lucasfariaslf It works with TensorFlow, either with its keras API and Callback (https://github.com/stared/livelossplot/blob/master/examples/keras.ipynb) or you can use bare API (https://github.com/stared/livelossplot/blob/master/examples/minimal.ipynb) logging whatever you wish.

Does it help, are are you looking for some specific functionality?

**Comment by lucasfariaslf** [comment]
@stared Indeed, you're totally right, I thought I couldn't use it with TensorFlow without Keras. The bare API works just fine...

Thank you for this awesome library, Piotr!
