### ISSUE TITLE
loss getting updated for each epoch but they are getting overwritten 

### ISSUE THREAD

**Issue by pragyan019** [stared/livelossplot#53]
Hi I am using https://github.com/qfgaohao/pytorch-ssd/blob/master/train_ssd.py code in jupyter notebook but the loss is getting updated and plotted for that epoch,giving a line parallel to x-axis.
[liveloss.txt](https://github.com/stared/livelossplot/files/3038811/liveloss.txt)
![livelossplot](https://user-images.githubusercontent.com/22221790/55481819-cdabe100-5640-11e9-8717-c14734685a85.png)

>

**Comment by stared** [comment]
The code you linked don't use `livelossplot` at all.

**Comment by pragyan019** [comment]
Please refer to the attached file (liveloss.txt),the GitHub link contains the original code

**Comment by stared** [comment]
@pragyan019 Does not look like an issue with livelossplot. And the next time please use https://gist.github.com, not a `txt` file. With some effort to solve it (e.g. `print(logs)`).
