### ISSUE TITLE
two small features request?

### ISSUE THREAD

**Issue by Jiraiyah** [stared/livelossplot#54]
@stared 
Hi. I would like to have two small features, take a look here : 

Mean squared error (cost function):
training   (min:    0.000, max:    0.000, cur:    0.000)
validation (min:    0.000, max:    0.000, cur:    0.000)

Accuracy:
training   (min:    0.549, max:    0.549, cur:    0.549)
validation (min:    0.355, max:    0.355, cur:    0.355)

this won't be enough for many purposes on precision, why? first 10 epochs of my neural starts right off of 0.00001 epoch loss !!!! the top table is pretty much useless with that precision.

Also, a nice thing to have before the tables would be a line that shows the finishing time on last epoch (how much time the last epoch took in total) side by side with the last epoch's number (when you run 3000 epochs, reading what epoch you are in from the chart is a headache)! I would appreciate if you add these two features. for the precision, maybe you can accept an integer into the function that would let us define how many digits in decimal place we need?

**Comment by Jiraiyah** [comment]
On a side note, how about having an alternative to use plotly instead of matplot? that library let us have offline charts in notebook but those charts support zooming and have nice features.

**Comment by stared** [comment]
@Jiraiyah There is an idea to create Bokeh backend, so one would be able to zoom plots: #19. Feel invited to implement it.

For printed logs - there will be a way to add custom log prints (and plots), but I need to think well about creating a good modularization (or ideally - someone else, with way more experience in software engineering in Python).

**Comment by Jiraiyah** [comment]
> @Jiraiyah There is an idea to create Bokeh backend, so one would be able to zoom plots: #19. Feel invited to implement it.
> 
> For printed logs - there will be a way to add custom log prints (and plots), but I need to think well about creating a good modularization (or ideally - someone else, with way more experience in software engineering in Python).

that person with good python experience ... definitely not me ! totally noob in python :)

**Comment by off99555** [comment]
Is this feature implemented yet? Just add `digits` as another parameter to `__init__()` function of `PlotLossesCallback()`.
