### ISSUE TITLE
Feauture request: Allow to simultaneously plot metric

### ISSUE THREAD

**Issue by renatobellotti** [stared/livelossplot#64]
It would be nice to have two subplots (or even more, if one wants to observe different metrics):

One should display the loss (as is currently possible), and the other one next to it should display a loss (selectable by user).

I hope other people would like that as well.

**Comment by stared** [comment]
@renatobellotti  Could you draw it?
I am not sure if you mean something in the line of ipython widgets, or something?

**Comment by renatobellotti** [comment]
I mean that you display two axes objects in the same figure. Something like [this](https://matplotlib.org/gallery/lines_bars_and_markers/cohere.html#sphx-glr-gallery-lines-bars-and-markers-cohere-py), but updated in realtime during training and with different content.

The x-axis of both graphs could be shared (number of epochs), and the y-axis of the top-most graph could contain the loss, while the other graph's y-axis represents the metric. Ideally, multiple subplots for different metrics would be nice.

**Comment by stared** [comment]
@renatobellotti With livelossplot 0.5.0 you can group metrics in plots as you wish.

**Comment by renatobellotti** [comment]
Nice, thank you!
