### ISSUE TITLE
Feature request: smoothing line to show trend

### ISSUE THREAD

**Issue by chithangduong** [stared/livelossplot#65]
It would be great if there is a trend line by smoothing the data points. This is especially useful for training GAN as the loss is usually noisy.

**Comment by stared** [comment]
@chithangduong  There is a functionality to write custom subplots: https://github.com/stared/livelossplot/blob/master/livelossplot/matplotlib_subplots.py, vide https://github.com/stared/livelossplot/blob/master/examples/2d_prediction_maps.ipynb. Please create one with smooth, and show a working example (as a Pull Request). 

It if works well, I will merge that (after a code review).
