### ISSUE TITLE
AttributeError: 'PlotLossesCallback' object has no attribute 'on_train_batch_begin'

### ISSUE THREAD

**Issue by maxouille** [stared/livelossplot#67]
Hi, 

I'm using this lib (which seems cool btw) and I got this error message : 
`AttributeError: 'PlotLossesCallback' object has no attribute 'on_train_batch_begin'`

I'm using TF 2.0 Beta 1 and Keras in python. 

Thx !

**Comment by ucekmez** [comment]
same here

**Comment by ucekmez** [comment]
you have to import the library as follows, if you want to use tf.keras:

`from livelossplot.tf_keras import PlotLossesCallback`
