### ISSUE TITLE
Option to dump plot into a file on every epoch

### ISSUE THREAD

**Issue by micmarty** [stared/livelossplot#68]
It would be very useful in case jupyter closes or training cell is rerun - plots will get lost.
Please consider adding this feature or maybe tell me how could I make it without manually modifying sources.

**Comment by stared** [comment]
@micmarty There is an option to do so: 

```
PlotLosses(fig_path="chart.png")```

or if you want to create a different one each epoch (instead of overwritting):
```
PlotLosses(fig_path="chart_{}.png")` ``

Vide https://github.com/stared/livelossplot/blob/master/livelossplot/generic_plot.py

Let me know if it works.
