### ISSUE TITLE
Losing epoch 1 and 2

### ISSUE THREAD

**Issue by djp3** [stared/livelossplot#69]
In the example here:
https://github.com/stared/livelossplot/blob/master/examples/minimal.ipynb
the x axis loses data for epoch 1 and 2 and begins plotting at 3 when there are 3 epochs to plot.

I encountered this in my own notebook and then checked this reference example to demonstrate the same behavior
![image](https://user-images.githubusercontent.com/121683/62240125-15dad600-b38b-11e9-82a3-e2e2c375869b.png)

**Comment by djp3** [comment]
I found the issue.  One can pass a parameter to the constructor to change this behavior:
liveplot = PlotLosses(skip_first=0)

**Comment by stared** [comment]
This was a long-required feature (vide #18), as very often first log-losses are very high and irrelevant to the further training process.

I understand it may be confusing (especially as there is no documentation), so indeed - concrete examples may be useful.

**Comment by djp3** [comment]
So all I'm proposing is to manually pass the skip_first parameter in the example so that the graph doesn't look broken (especially as it is the "low-level" API example)  No change in the main code base necessary given the history that you cite.

**Comment by stared** [comment]
Yes, it's a fair point that for this minimalistic examples skipping first few entries in confusing. I accepted your PR. Thank you, @djp3 !
