### ISSUE TITLE
Cannot log to Tensorboard because of automatic folder name

### ISSUE THREAD

**Issue by PhilMacKay** [stared/livelossplot#75]
When using Tensorboard logging, it will try to create a directory with `time_str = datetime.now().isoformat()[:-7].replace("T", " ")`.
However, the isoformat includes the ":" character which cannot be used in a file path.

The line should be updated to replace a blacklist of characters. This may vary from one OS to another, but on Windows 10, it's not possible to use Tensorboard logging without tweaking the `time_str` variable.

**Comment by stared** [comment]
@PhilMacKay Thank you for bringing this issue (I tested it on macOS and Ubuntu, but not Windows).

Yes, it is likely system dependent. If you create a PR solving that issue (e.g. `.replace(":", "_")`), I will gladly accept that.

**Comment by stared** [comment]
Solved with #77.
