### ISSUE TITLE
hard code epoch of xlabel, need enhance

### ISSUE THREAD

**Issue by sphinx-jiang** [stared/livelossplot#80]
def draw_plot
....
        plt.xlabel('epoch')
        plt.legend(loc='center right')

could it support the input xlabel?

**Comment by stared** [comment]
Closing this issue as related to version prior to livelossplot 0.5.0. 

For custom plots, see https://github.com/stared/livelossplot/blob/master/livelossplot/outputs/matplotlib_subplots.py and generate one.
